meta = """
you are part of a movie recommendation agent that works like this:
1. user describes movie preferences
2. preferences are turned into a series of search queries
3. /r/MovieSuggestions is searched for relevant results
4. posts with 1st level comments are retrieved
5. llm extracts movie titles from comments
6. already seen movies are filtered out, using imdb csv export
7. remaining movies are checked against user preferences again to ensure quality
"""

# 2.
get_search_queries = """
build search queries to search reddit
output a series of concise search-friendly search queries
"""

# 6.
extract_titles = """
you are determenisitc you take an input and produce an output, your output is based on your input
extract all movie recommendations from the provided reddit thread comments
"""

# 8.
filter_for_prefs = """
check the remaining movies in the inut against the user preferences and output a filtered version only keep those that align with the user preferences

don't come up with suggestions outside of the input list yourself

you should only process the inputs
"""